# Generated by Django 6.0.4 on 2026-04-28 17:23

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_role_values(apps, schema_editor):
    User = apps.get_model("App", "User")
    Device = apps.get_model("App", "Device")
    DeviceAssignment = apps.get_model("App", "DeviceAssignment")

    User.objects.filter(role="head_office").update(role="head_office_manager", is_staff=True)

    for device in Device.objects.all():
        active_assignment = (
            DeviceAssignment.objects.filter(device=device, returned_at__isnull=True)
            .order_by("-assigned_at")
            .first()
        )
        if active_assignment:
            device.branch_id = active_assignment.branch_id
            device.status = "not_available"
        else:
            device.status = "available"
        device.save(update_fields=["branch", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name', 'serial_number']},
        ),
        migrations.AlterModelOptions(
            name='deviceassignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='headoffice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AddField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='App.branch'),
        ),
        migrations.AddField(
            model_name='request',
            name='approved_by_branch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='approved_by_head_office_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments', to='App.branch'),
        ),
        migrations.AlterField(
            model_name='headoffice',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head_office_manager', 'Head Office Manager'), ('branch_manager', 'Branch Manager'), ('employee', 'Employee')], default='employee', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('head_office', 'name')},
        ),
        migrations.RunPython(migrate_existing_role_values, migrations.RunPython.noop),
    ]
