# Generated by Django 6.0.4 on 2026-04-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_branch_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='head_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='App.headoffice'),
        ),
    ]
