# Generated by Django 6.0.4 on 2026-04-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_employee_head_office'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deviceassignment',
            name='unique_active_device_assignment',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
    ]
