# Generated by Django 6.0.3 on 2026-05-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_restore_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
    ]
