# Generated by Django 6.0.4 on 2026-05-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='deviceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('device',), name='unique_active_device_assignment'),
        ),
    ]
