# Generated by Django 6.0.3 on 2026-05-01 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_device_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('device_assigned', 'Device Assigned'), ('device_reassigned', 'Device Reassigned'), ('device_returned', 'Device Returned'), ('request_created', 'Request Created'), ('request_approved_by_branch', 'Request Approved by Branch'), ('request_approved_by_head_office', 'Request Approved by Head Office'), ('request_rejected', 'Request Rejected'), ('request_resolved', 'Request Resolved'), ('system_update', 'System Update')], default='system_update', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='deviceassignment',
            name='unique_active_device_assignment',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        migrations.AddField(
            model_name='device',
            name='assign_to_all_branches',
            field=models.BooleanField(default=False, help_text='If True, this device is available to all branches in the system.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='App.device'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_notifications', to='App.employee'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='App.request'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
