# Generated by Django 6.0.3 on 2026-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assign_to_all_branches',
            field=models.BooleanField(default=False, help_text='If True, this device is assigned to all branches and head office.'),
        ),
    ]
